language: node_js
node_js:
  - 11
before_install:
  - npm i -g firebase-tools
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  project: fir-travis-asthamor
  skip_cleanup: true
  token:
    secure: NoepDUdGe2VyYWJCIcFqKWJn5myPmndm6mMvLr7f3/aZo/UWCtDci4ovXpoK6inzme0Zg0lyZj/KT1gnKW28e5Gj3ziJwBuXyhRH0xwiAataUi5GFyHEUIHX62FPlK5MgUceAlub4JatAkDB8jK3Y9FrDhVoY4rZVKKL8YMLUJLX/CWSk3zIWIKnnfGGYis3BhOUnTycCqUzR+AmJjjWITaHkpWrkotfmsPy+wTVR2cn/611hZLhtjPE8rkFXzYpEuZdpuNZMLQJUsUae9wLOBSbtIhkazehS4EgRiQEcC99EcSCHNDRO6dWYw5GPe8jhNYgQWWFrjkOfn1tZad1rzOh8dpv4kRBLlZM3yPKdFLeaCz4nTr07MtE08krgppFh7o2p3B+8OEukEpIHnn+oiMwBSDuM+fPF5sUFUizaYNFhXaC77WdbfBl1BuHfFa6E3fZ2GXEyBpq9e/Gt5RUvH272hi603iI+hoT0gwfqBK8hfIqCguUiUrqc9ElWIrQzMFjOifc7eVnPZTjsmwQsyzMqbDI9vsAO/y6+f9j3Ljzpc5Wc/+thH27bJFxV0BkbZOAHwtiY+J55G7aivy6hyJk3Bl8NubCGGtiNLnK3wohcWe4i3sAcvSbCEpDKcF/WNWzMPyPnZVw0nWqrLZTNLEjYcj41+otAJVRN+y24/8=
