language: node_js
node_js:
  - 11
before_install:
  - npm i -g firebase-tools
cache:
  directories:
    - node_modules
script:
  - yarn run build
deploy:
  provider: firebase
  project: demo-travis
  skip_cleanup: true
  token:
    secure: fYhhCPwlLGtZ4NWcPDK0RsFfDv2bviTsi7Zmn5To/t6ETdvN2e0wEfOXSdADveW838wfiRsnBAxfzyAhTiOzkBOEjs/bAG34obHeOQ/oG4jVNyouiatNgRn2YPfHtWTitExtqYs5j3KlcqLctl2LrBf0cRo5qZLfq+sOcmuZejt1a8PiGH6G5NmL4xjVQLMEVZDaWkvXHl2B+dV1gIlzTIsNm2tFY26erC91J6QTp6Ep66fli/Gg9z5QrWH/c9+9tL9rxGKor60FEx0jfxYK8pgwfR4sHLcZgmAypBu9WI+j1Br+KFEvfM6f1ZK81s7TFzTRRN3AauuX4hWAvY+Ad8DDu6UuKm0BB4646tnCVtJ/+ZcXC0xNLsICdfg0cvYV7LNUV114yGA1LAC9W1w/HqtnlehfqZuRYHUYg8YWxI8RzCHCILghuwmaCJYVnRYIzvY93UaiV6p8+pqOvri12BaWCqc1QDqNzB95AXQ21xPyD2S5s9S09pgM2fHQQSnw9w6ywzWhdpPCfupaTybHPtn7M4rLYpBdCHMTjfGB9yVqhwJdVe1jIitdqTlPKza8mPOPTEkfvq104feDC5n5Y+R9+GSHUKW/q0ScRyg5EuJilKilPZLe42pvNLDgWG9njBNQ8i3GliqtMI7tF3Z/ABfp4HBYdbNSmDNREtG+gSs=
env:
  global:
    secure: X+uDyE1P3l/6WAj8ZRoU0S0gKHmgPGShvasJxgwo53BbXHouFalOM+pBFhQAWqzIj0H6OBLBnEtF3COsaMVxDrvR2uWCe4SmUZbkkDYT24S45IpFotTVI66agAGckcKDoe2mEkElUYa07YVue5lkfH5iksoGH/rtQlI5flObEMnpY4lSTi1q2IewzHb6upH778/I9kWEJSair+vBMh7mB3dr2QdiSrX7wU/6tFytf5cXHwWp/QnQxyY5IBCF8O7nbkldMSe0SvtDLiEcnHeFVuJ7Rkwt8RMx+S51GbMrSsrMtbDNYwUDuP+jo1W9VUGH6AMJB8XJQ5sQ6jBVT2o1DS+m5rArksy4cPTUGMDYP36Vfn5GhVlLo2nkoEE38bYRHIAgKsCHR46E1Adh2ab2GcKW+y1foORza4WJD1zREfNkGZ0OeNld8qbD4Ww/rzDyEj+v/eO2skC0a5TFSp8NiZ3YFqTLpbaDI+LJxb0WBivFXZgA7jwO3RqqyN+3L1NbIHoer8aC0/lnHU19A8AJ1Hs0YB/7hD2fdkKp5JhFZBQG+RZQMN39YjTohxv+7JXHrDwkmb+Lh7aMGqDGo7FzVhFni/gHetTQnY+Yw0JAwmawx7h8MafyRB2OZywFWI/lsFeQLAoM5IDHsqDifrjF6XimGBeYUoWqhf6Bkgxr6hM=
